version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.7
 build: 
  commands:
   - sam package --template-file template.yml --s3-bucket b0deploy --output-template-file packaged-template.yml
artifacts:
 type: zip
 files:
  - template.yml
  - outputtemplate.yml