version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.7
 build: 
  commands:
    - touch source1_file
    - cd $CODEBUILD_SRC_DIR_source2
    - touch source2_file
artifacts:
  type: zip
  files:
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - source1_file
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR_source2
      files:
        - source2_file