AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-3
Description: test
Resources:
  myLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: myLambdaFunction
      Handler: LF1_index-photos.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda