AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: test
Resources:
  index-photos-test:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index-photos-test.lambda_handler
      Runtime: python3.7
      FunctionName: index-photos-test
      CodeUri: ./lambda