AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda
Resources:
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: $FUNCTION_NAME.lambda_handler
      Runtime: python3.7
      FunctionName: $FUNCTION_NAME
      CodeUri: ./src/src2 #Directory the source file is
      Timeout: 10