AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda
Resources:
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: LF2.lambda_handler
      Runtime: python3.7
      FunctionName: LF2
      CodeUri: ./src2 #Directory the source file is
      Timeout: 10